### ISSUE TITLE
set victory conditions

### ISSUE THREAD

**Issue by andy5995** [zetaglest/chess#1]
The scenario needs to know when victory has been achieved

**Comment by Jammyjamjamman** [comment]
Win condition is normally "checkmate". I would assume in this case, that means "when the opponent's king dies", but who is the king? Or is the win condition when your opponent runs out of units?

**Comment by andy5995** [comment]
Maybe the fire golem? Or the shaman? The final version, which I couldn't find, the shaman was king. I'm open to suggestions though

**Comment by Jammyjamjamman** [comment]
The king should be pretty strong so he can hide in units. Is the shaman strong in this? Maybe we can make him strong?

**Comment by andy5995** [comment]
Completed by @Jammyjamjamman and closed in https://github.com/zetaglest/chess/commit/9bed7b5e40b6b0ff139e81c91567baad3f7b25e7
